### ISSUE TITLE
classDirectory needs to be dynamic

### ISSUE THREAD

**Issue by fommil** [typesafehub/sbt-tojar#3]
line 77-ish, you need to define a dynamic task. Recall that `.value` on a key will result in its task being evaluated before your task runs, even if you don't use it.

I trust that you don't mind if I use this exact piece of code in my Scala World talk later this year as a perfect example of how experienced Scala developers get confused by the macros in sbt and why the "long form" `map` / `flatMap` approach is far superior for anything non-trivial :wink:

**Comment by fommil** [comment]
btw, on a more practical level (and how I came upon this) I had a conflict when using it in something like the `plugin` project of https://github.com/fommil/imaginary-friend where sbt was complaining about missing keys.

My quick workaround was to disable the `allRequirements`

**Comment by cunei** [comment]
Hello @fommil,
The reference to classDirectory cannot be changed into a dynamic task, because classDirectory is not a task: it is a setting. Concerning the conflict that you encountered, I tried to enable the straight-to-jar plugin on the `plugin` subproject of `imaginary-friend`, and compilation completed successfully in my tests:

```
> set straightToJar in plugin := true
[info] Defining plugin/*:straightToJar
[info] The new value will be used by plugin/*:clean, plugin/*:compilers and 4 others.
[info]  Run `last` for details.
[info] Reapplying settings...
[info] Set current project to root (in build file:/home/cunei/activities/testing-straight-to-jar/imaginary-friend/)
> plugin/compile
[info] Formatting 1 Scala source {file:/home/cunei/activities/testing-straight-to-jar/imaginary-friend/}plugin(compile) ...
[info] Compiling 1 Scala source to /home/cunei/activities/testing-straight-to-jar/imaginary-friend/plugin/target/scala-2.10/plugin_2.10-1.0.0-SNAPSHOT.jar...
[success] Total time: 6 s, completed Mar 23, 2016 3:04:34 PM
```

Could you please supply some additional information concerning the exact error message that you encountered?
